# Generated by Django 3.1.5 on 2021-04-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_token_app', '0002_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdetails',
        ),
    ]
